spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: application
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    root: info